import { Product } from "@/components/product-card"

export interface ProductDetail extends Product {
  gallery: string[]
  videos?: string[]
  description: string
  specifications: Record<string, string>
  colors?: string[]
}

export const productsData: Record<string, ProductDetail> = {
  "1": {
    id: "1",
    name: "RAMO LILIUM PERFUMADO",
    price: 0,
    image: "/FOTOS/PRIMAVERA VERANO/placeholder-lilium.jpg",
    category: "Arreglos Florales",
    inStock: true,
    featured: true,
    gallery: [
      "/FOTOS/PRIMAVERA VERANO/placeholder-lilium.jpg",
    ],
    description:
      "Hermoso ramo de lilium perfumado, reconocido por su fragancia exquisita y elegancia natural. Cada flor es cuidadosamente seleccionada por su frescura y aroma distintivo. Perfecto para ocasiones especiales que requieren sofisticación y belleza.",
    specifications: {
      "Cantidad de flores": "8-10 unidades",
      "Tipo de flor": "Lilium perfumado",
      "Envoltorio": "Papel de seda elegante",
      "Duración": "7-10 días",
      "Cuidados": "Agua fresca diaria",
      "Ocasión": "Elegancia, celebraciones",
    },
    colors: ["Blanco", "Rosa", "Amarillo", "Naranja"],
  },
  "2": {
    id: "2",
    name: "RAMO LILIUM CLÁSICO",
    price: 0,
    image: "/FOTOS/PRIMAVERA VERANO/RAMO-POR-6-LILIUMS-800.jpg",
    category: "Arreglos Florales",
    inStock: true,
    featured: true,
    gallery: [
      "/FOTOS/PRIMAVERA VERANO/RAMO-POR-6-LILIUMS-800.jpg",
    ],
    description:
      "Ramo clásico de lilium, diseñado con la elegancia tradicional que caracteriza a estas magníficas flores. Su belleza atemporal y porte majestuoso lo convierten en una elección perfecta para cualquier ocasión especial.",
    specifications: {
      "Cantidad de flores": "6-8 unidades",
      "Tipo de flor": "Lilium clásico",
      "Envoltorio": "Papel kraft premium",
      "Duración": "7-10 días",
      "Estilo": "Clásico tradicional",
      "Ocasión": "Versatil, elegante",
    },
  },
  "4": {
    id: "4",
    name: "RAMO GERBERAS",
    price: 0,
    image: "/FOTOS/PRIMAVERA VERANO/2 (GERBERAS).jpg",
    category: "Arreglos Florales",
    inStock: true,
    featured: true,
    gallery: [
      "/FOTOS/PRIMAVERA VERANO/2 (GERBERAS).jpg",
    ],
    description: "Alegre ramo de gerberas que irradia color y vitalidad. Estas flores simbolizan la felicidad y el optimismo, perfectas para transmitir alegría y buenos deseos en cualquier ocasión.",
    specifications: {
      "Cantidad de flores": "8-12 unidades",
      "Tipo de flor": "Gerberas mixtas",
      "Colores": "Variados y vibrantes",
      "Duración": "7-10 días",
      "Estilo": "Moderno y alegre",
      "Ocasión": "Cumpleaños, celebraciones",
    },
  },
  "5": {
    id: "5",
    name: "RAMO LISIANTHUS",
    price: 0,
    image: "/FOTOS/PRIMAVERA VERANO/3 (LISIANTHUS).jpg",
    category: "Arreglos Florales",
    inStock: true,
    featured: true,
    gallery: [
      "/FOTOS/PRIMAVERA VERANO/3 (LISIANTHUS).jpg",
    ],
    description: "Exquisito ramo de lisianthus, flores conocidas por su textura sedosa y apariencia delicada. Su elegancia natural y variedad de colores suaves las convierten en una elección perfecta para ocasiones refinadas.",
    specifications: {
      "Cantidad de flores": "10-15 unidades",
      "Tipo de flor": "Lisianthus premium",
      "Textura": "Sedosa y delicada",
      "Duración": "8-12 días",
      "Estilo": "Elegante y refinado",
      "Ocasión": "Bodas, eventos especiales",
    },
  },
  "6": {
    id: "6",
    name: "RAMO LISIANTHUS PICOTE",
    price: 0,
    image: "/FOTOS/PRIMAVERA VERANO/3 (LISIANTHUS PICOTE).jpg",
    category: "Arreglos Florales",
    inStock: true,
    gallery: [
      "/FOTOS/PRIMAVERA VERANO/3 (LISIANTHUS PICOTE).jpg",
    ],
    description: "Ramo especial de lisianthus picote, caracterizado por sus bordes delicadamente decorados que añaden un toque distintivo y sofisticado a estas ya elegantes flores.",
    specifications: {
      "Cantidad de flores": "8-12 unidades",
      "Tipo de flor": "Lisianthus picote",
      "Característica": "Bordes decorativos",
      "Duración": "8-12 días",
      "Estilo": "Único y distintivo",
      "Ocasión": "Eventos exclusivos",
    },
  },
  "7": {
    id: "7",
    name: "RAMO CLAVELINAS",
    price: 0,
    image: "/FOTOS/PRIMAVERA VERANO/4 (CLAVELINAS).jpg",
    category: "Ramos",
    inStock: true,
    featured: true,
    gallery: [
      "/FOTOS/PRIMAVERA VERANO/4 (CLAVELINAS).jpg",
    ],
    description: "Tierno ramo de clavelinas, flores pequeñas pero llenas de encanto y delicadeza. Su tamaño compacto y variedad de colores las hacen perfectas para arreglos delicados y expresiones sutiles de cariño.",
    specifications: {
      "Cantidad de flores": "15-20 unidades",
      "Tipo de flor": "Clavelinas mixtas",
      "Tamaño": "Pequeño y delicado",
      "Duración": "10-14 días",
      "Estilo": "Tierno y romántico",
      "Ocasión": "Detalles especiales",
    },
  },
  "8": {
    id: "8",
    name: "RAMO JAZMÍNES",
    price: 0,
    image: "/FOTOS/PRIMAVERA VERANO/5 (JAZMIN).jpg",
    category: "Arreglos Florales",
    inStock: true,
    featured: true,
    gallery: [
      "/FOTOS/PRIMAVERA VERANO/5 (JAZMIN).jpg",
    ],
    description: "Aromático ramo de jazmines, reconocido por su fragancia intensa y embriagadora. Estas flores blancas y delicadas simbolizan la pureza y el amor, llenando cualquier espacio con su perfume característico.",
    specifications: {
      "Cantidad de flores": "12-18 unidades",
      "Tipo de flor": "Jazmín aromático",
      "Color": "Blanco puro",
      "Fragancia": "Intensa y dulce",
      "Duración": "5-8 días",
      "Ocasión": "Romántica, especial",
    },
  },
  "9": {
    id: "9",
    name: "RAMO ASTROMELIAS",
    price: 0,
    image: "/FOTOS/PRIMAVERA VERANO/placeholder-astromelias.jpg",
    category: "Arreglos Florales",
    inStock: true,
    featured: true,
    gallery: [
      "/FOTOS/PRIMAVERA VERANO/placeholder-astromelias.jpg",
    ],
    description: "Versátil ramo de astromelias, flores conocidas por su durabilidad y variedad de colores. Simbolizan la amistad y la devoción, siendo una excelente opción para múltiples ocasiones.",
    specifications: {
      "Cantidad de flores": "10-15 unidades",
      "Tipo de flor": "Astromelias mixtas",
      "Colores": "Variados",
      "Duración": "10-14 días",
      "Estilo": "Versátil y duradero",
      "Ocasión": "Amistad, gratitud",
    },
  },
  "10": {
    id: "10",
    name: "RAMO ROSAS",
    price: 0,
    image: "/FOTOS/PRIMAVERA VERANO/7 (ROSAS).jpg",
    category: "Ramos",
    inStock: true,
    featured: true,
    gallery: [
      "/FOTOS/PRIMAVERA VERANO/7 (ROSAS).jpg",
    ],
    description: "Clásico ramo de rosas, símbolo universal del amor y la pasión. Cada rosa es cuidadosamente seleccionada por su perfección y frescura, creando un regalo atemporal para expresar los sentimientos más profundos.",
    specifications: {
      "Cantidad de rosas": "12 unidades",
      "Tipo de rosa": "Rosa premium",
      "Envoltorio": "Papel de seda elegante",
      "Duración": "7-10 días",
      "Cuidados": "Agua fresca diaria",
      "Ocasión": "Amor, aniversarios",
    },
    colors: ["Rojo", "Rosa", "Blanco", "Amarillo"],
  },
  "11": {
    id: "11",
    name: "RAMO ROSAS SPRAY",
    price: 0,
    image: "/FOTOS/PRIMAVERA VERANO/7 (ROSAS SPRAY).jpg",
    category: "Arreglos Florales",
    inStock: true,
    featured: true,
    gallery: [
      "/FOTOS/PRIMAVERA VERANO/7 (ROSAS SPRAY).jpg",
    ],
    description: "Encantador ramo de rosas spray, caracterizado por sus múltiples flores pequeñas por tallo que crean un efecto abundante y romántico. Perfectas para crear arreglos voluminosos y llenos de vida.",
    specifications: {
      "Cantidad de tallos": "8-10 unidades",
      "Tipo de rosa": "Rosa spray",
      "Flores por tallo": "3-5 pequeñas",
      "Duración": "7-10 días",
      "Estilo": "Abundante y romántico",
      "Ocasión": "Romántica, decorativa",
    },
  },
  "12": {
    id: "12",
    name: "RAMO DIANTHUS",
    price: 0,
    image: "/FOTOS/PRIMAVERA VERANO/8 (DIANTHUS).jpg",
    category: "Arreglos Florales",
    inStock: true,
    featured: true,
    gallery: [
      "/FOTOS/PRIMAVERA VERANO/8 (DIANTHUS).jpg",
    ],
    description: "Delicado ramo de dianthus, flores conocidas por su fragancia dulce y pétalos dentados distintivos. Su belleza sutil y colores suaves las convierten en una elección perfecta para expresar ternura y cariño.",
    specifications: {
      "Cantidad de flores": "12-18 unidades",
      "Tipo de flor": "Dianthus perfumado",
      "Fragancia": "Dulce y sutil",
      "Duración": "8-12 días",
      "Estilo": "Delicado y tierno",
      "Ocasión": "Ternura, cariño",
    },
  },
  "13": {
    id: "13",
    name: "RAMO GIRASOL",
    price: 0,
    image: "/FOTOS/PRIMAVERA VERANO/9 (GIRASOL).jpg",
    category: "Arreglos Florales",
    inStock: true,
    featured: true,
    gallery: [
      "/FOTOS/PRIMAVERA VERANO/9 (GIRASOL).jpg",
    ],
    description: "Radiante ramo de girasoles, flores que simbolizan la felicidad, la energía positiva y la vitalidad. Su tamaño imponente y color amarillo brillante transmiten alegría y optimismo instantáneamente.",
    specifications: {
      "Cantidad de flores": "5-8 unidades",
      "Tipo de flor": "Girasol grande",
      "Color": "Amarillo brillante",
      "Duración": "7-10 días",
      "Estilo": "Alegre y energético",
      "Ocasión": "Celebraciones, alegría",
    },
  },
  "14": {
    id: "14",
    name: "MOLUCELLA",
    price: 0,
    image: "/FOTOS/PRIMAVERA VERANO/10 (MOLUCELLA).jpg",
    category: "Ambientaciones",
    inStock: true,
    featured: true,
    gallery: [
      "/FOTOS/PRIMAVERA VERANO/10 (MOLUCELLA).jpg",
    ],
    description: "Única molucella, conocida como 'campanas de Irlanda', una flor distintiva por su forma y color verde característico. Perfecta para arreglos modernos y contemporáneos que buscan originalidad.",
    specifications: {
      "Cantidad de tallos": "8-12 unidades",
      "Tipo de flor": "Molucella (Campanas de Irlanda)",
      "Color": "Verde característico",
      "Duración": "10-14 días",
      "Estilo": "Moderno y único",
      "Ocasión": "Decoración contemporánea",
    },
  },
  "15": {
    id: "15",
    name: "ESTATIS",
    price: 0,
    image: "/FOTOS/PRIMAVERA VERANO/11 (ESTATIS).jpg",
    category: "Servicio Semanal",
    inStock: true,
    featured: true,
    gallery: [
      "/FOTOS/PRIMAVERA VERANO/11 (ESTATIS).jpg",
    ],
    description: "Ramo de estatis, flores con textura papácea y colores vibrantes que se mantienen hermosas por mucho tiempo. Ideales para arreglos que requieren durabilidad y un toque rústico elegante.",
    specifications: {
      "Cantidad de tallos": "10-15 unidades",
      "Tipo de flor": "Estatis mixtas",
      "Textura": "Papácea, seca",
      "Duración": "3-4 semanas",
      "Estilo": "Rústico elegante",
      "Ocasión": "Decoración duradera",
    },
  },
  "16": {
    id: "16",
    name: "RAMO ALELÍ",
    price: 0,
    image: "/FOTOS/PRIMAVERA VERANO/12 (ALELÍ).jpg",
    category: "Arreglos Florales",
    inStock: true,
    featured: true,
    gallery: [
      "/FOTOS/PRIMAVERA VERANO/12 (ALELÍ).jpg",
    ],
    description: "Aromático ramo de alelí, flores conocidas por su fragancia dulce e intensa que se acentúa por las noches. Sus flores en racimo crean un efecto visual hermoso y llenan el ambiente de perfume.",
    specifications: {
      "Cantidad de tallos": "8-12 unidades",
      "Tipo de flor": "Alelí perfumado",
      "Fragancia": "Dulce e intensa",
      "Duración": "6-9 días",
      "Estilo": "Aromático y romántico",
      "Ocasión": "Noches románticas",
    },
  },
  "17": {
    id: "17",
    name: "RAMO CONEJITOS",
    price: 0,
    image: "/FOTOS/PRIMAVERA VERANO/13 (CONEJITOS).jpeg",
    category: "Arreglos Florales",
    inStock: true,
    featured: true,
    gallery: [
      "/FOTOS/PRIMAVERA VERANO/13 (CONEJITOS).jpeg",
    ],
    description: "Peculiar ramo de conejitos, flores con una forma distintiva que recuerda a pequeños conejitos. Su apariencia única y tierna las convierte en una elección perfecta para regalos especiales y decoraciones originales.",
    specifications: {
      "Cantidad de tallos": "15-20 unidades",
      "Tipo de flor": "Conejitos (Antirrhinum)",
      "Forma": "Distintiva, tipo conejito",
      "Duración": "7-10 días",
      "Estilo": "Único y tierno",
      "Ocasión": "Regalos especiales",
    },
  },
  "18": {
    id: "18",
    name: "RAMO CALAS",
    price: 0,
    image: "/FOTOS/PRIMAVERA VERANO/14 (CALAS).jpg",
    category: "Ramos",
    inStock: true,
    featured: true,
    gallery: [
      "/FOTOS/PRIMAVERA VERANO/14 (CALAS).jpg",
    ],
    description: "Sofisticado ramo de calas, flores de forma escultural y elegancia incomparable. Su línea simple pero impactante las convierte en símbolos de magnificencia y belleza refinada.",
    specifications: {
      "Cantidad de flores": "6-9 unidades",
      "Tipo de flor": "Calas premium",
      "Forma": "Escultural elegante",
      "Duración": "8-12 días",
      "Estilo": "Sofisticado y moderno",
      "Ocasión": "Eventos elegantes",
    },
  },
  "19": {
    id: "19",
    name: "RAMO AZUCENAS",
    price: 0,
    image: "/FOTOS/PRIMAVERA VERANO/15 (AZUCENA).jpg",
    category: "Arreglos Florales",
    inStock: true,
    featured: true,
    gallery: [
      "/FOTOS/PRIMAVERA VERANO/15 (AZUCENA).jpg",
    ],
    description: "Majestuoso ramo de azucenas, flores que simbolizan la pureza y la renovación. Su tamaño imponente y belleza natural las convierten en una elección perfecta para ocasiones significativas y ceremonias especiales.",
    specifications: {
      "Cantidad de flores": "5-8 unidades",
      "Tipo de flor": "Azucenas grandes",
      "Color": "Blanco puro predominante",
      "Duración": "7-10 días",
      "Estilo": "Majestuoso y puro",
      "Ocasión": "Ceremonias, pureza",
    },
  },
  "20": {
    id: "20",
    name: "RAMO PEONIAS",
    price: 0,
    image: "/FOTOS/PRIMAVERA VERANO/33.jpg",
    category: "Arreglos Florales",
    inStock: true,
    featured: true,
    gallery: [
      "/FOTOS/PRIMAVERA VERANO/33.jpg",
    ],
    description: "Exuberante ramo de peonías, consideradas las reinas de las flores por su volumen y belleza excepcional. Simbolizan la prosperidad, el honor y la riqueza, siendo perfectas para celebraciones importantes.",
    specifications: {
      "Cantidad de flores": "5-7 unidades",
      "Tipo de flor": "Peonías premium",
      "Volumen": "Muy abundante",
      "Duración": "5-8 días",
      "Estilo": "Lujoso y exuberante",
      "Ocasión": "Celebraciones importantes",
    },
  },
  "21": {
    id: "21",
    name: "RAMO MARIMONIAS",
    price: 0,
    image: "/FOTOS/PRIMAVERA VERANO/17 (MARIMONIAS).jpg",
    category: "Arreglos Florales",
    inStock: true,
    featured: true,
    gallery: [
      "/FOTOS/PRIMAVERA VERANO/17 (MARIMONIAS).jpg",
    ],
    description: "Delicado ramo de marimonias, flores pequeñas pero llenas de encanto que crean una textura suave y romántica. Perfectas para arreglos que buscan transmitir ternura y delicadeza.",
    specifications: {
      "Cantidad de tallos": "12-18 unidades",
      "Tipo de flor": "Marimonias delicadas",
      "Textura": "Suave y romántica",
      "Duración": "8-12 días",
      "Estilo": "Tierno y delicado",
      "Ocasión": "Expresiones de ternura",
    },
  },
  "22": {
    id: "22",
    name: "ALCAUCIL",
    price: 0,
    image: "/FOTOS/PRIMAVERA VERANO/18 (ALCAUCIL).jpg",
    category: "Arreglos Florales",
    inStock: true,
    gallery: [
      "/FOTOS/PRIMAVERA VERANO/18 (ALCAUCIL).jpg",
    ],
    description: "Rústico alcaucil ornamental, que aporta una textura única y natural a los arreglos florales. Su apariencia silvestre y carácter distintivo lo convierten en perfecto para decoraciones con estilo campestre y natural.",
    specifications: {
      "Cantidad de piezas": "5-8 unidades",
      "Tipo": "Alcaucil ornamental",
      "Textura": "Rústica y natural",
      "Duración": "2-3 semanas",
      "Estilo": "Rústico campestre",
      "Ocasión": "Decoración natural",
    },
  },
  "23": {
    id: "23",
    name: "CARDOS",
    price: 0,
    image: "/FOTOS/PRIMAVERA VERANO/19 (CARDOS).jpg",
    category: "Arreglos Florales",
    inStock: true,
    gallery: [
      "/FOTOS/PRIMAVERA VERANO/19 (CARDOS).jpg",
    ],
    description: "Silvestre ramo de cardos, flores con una belleza rústica única y distintivo color azul-violáceo. Aportan textura y personalidad a los arreglos, siendo perfectos para decoraciones con carácter natural y bohemio.",
    specifications: {
      "Cantidad de tallos": "8-12 unidades",
      "Tipo de flor": "Cardos silvestres",
      "Color": "Azul-violáceo",
      "Duración": "10-15 días",
      "Estilo": "Silvestre y bohemio",
      "Ocasión": "Decoración rústica",
    },
  },
  "24": {
    id: "24",
    name: "RAMO FRESIAS",
    price: 0,
    image: "/FOTOS/PRIMAVERA VERANO/20 (FRESIAS).jpg",
    category: "Arreglos Florales",
    inStock: true,
    featured: true,
    gallery: [
      "/FOTOS/PRIMAVERA VERANO/20 (FRESIAS).jpg",
    ],
    description: "Perfumado ramo de fresias, flores conocidas por su fragancia fresca y delicada. Sus colores pastel y aroma característico las convierten en símbolos de inocencia y amistad sincera.",
    specifications: {
      "Cantidad de tallos": "10-15 unidades",
      "Tipo de flor": "Fresias perfumadas",
      "Fragancia": "Fresca y delicada",
      "Duración": "7-10 días",
      "Estilo": "Fresco y delicado",
      "Ocasión": "Amistad, pureza",
    },
  },
  "25": {
    id: "25",
    name: "GLADIOLOS",
    price: 0,
    image: "/FOTOS/PRIMAVERA VERANO/21 (GLADIOLOS).jpg",
    category: "Arreglos Florales",
    inStock: true,
    gallery: [
      "/FOTOS/PRIMAVERA VERANO/21 (GLADIOLOS).jpg",
    ],
    description: "Imponente ramo de gladiolos, flores de porte vertical y elegancia clásica. Su altura majestuosa y variedad de colores los convierten en perfectos para arreglos monumentales y decoraciones ceremoniales.",
    specifications: {
      "Cantidad de tallos": "6-10 unidades",
      "Tipo de flor": "Gladiolos grandes",
      "Altura": "70-90 cm",
      "Duración": "7-12 días",
      "Estilo": "Majestuoso y ceremonial",
      "Ocasión": "Ceremonias, eventos",
    },
  },
  "26": {
    id: "26",
    name: "RAMO GODETIAS",
    price: 0,
    image: "/FOTOS/PRIMAVERA VERANO/22 (GODETIAS).jpg",
    category: "Arreglos Florales",
    inStock: true,
    featured: true,
    gallery: [
      "/FOTOS/PRIMAVERA VERANO/22 (GODETIAS).jpg",
    ],
    description: "Sedoso ramo de godetias, flores con pétalos de textura satinada y colores suaves que evocan la delicadeza de la seda. Perfectas para arreglos románticos y decoraciones que buscan elegancia sutil.",
    specifications: {
      "Cantidad de tallos": "12-18 unidades",
      "Tipo de flor": "Godetias sedosas",
      "Textura": "Satinada y suave",
      "Duración": "6-9 días",
      "Estilo": "Romántico y sutil",
      "Ocasión": "Romance, elegancia",
    },
  },
  "27": {
    id: "27",
    name: "REINA MARGARITA",
    price: 0,
    image: "/FOTOS/PRIMAVERA VERANO/23 (REINA MARGARITA).jpg",
    category: "Arreglos Florales",
    inStock: true,
    featured: true,
    gallery: [
      "/FOTOS/PRIMAVERA VERANO/23 (REINA MARGARITA).jpg",
    ],
    description: "Abundante ramo de reina margarita, flores que destacan por su profusión de pétalos y colores vibrantes. Su naturaleza generosa y alegre las convierte en perfectas para celebraciones y expresiones de felicidad.",
    specifications: {
      "Cantidad de tallos": "10-15 unidades",
      "Tipo de flor": "Reina margarita",
      "Pétalos": "Abundantes y coloridos",
      "Duración": "8-12 días",
      "Estilo": "Alegre y abundante",
      "Ocasión": "Celebraciones, alegría",
    },
  },
  "28": {
    id: "28",
    name: "AMBIENTACIÓN DE EVENTOS",
    price: 0,
    image: "/videos/eventos/1.mp4",
    category: "Ambientación de Eventos",
    inStock: true,
    gallery: [],
    videos: [
      "/videos/eventos/1.mp4",
      "/videos/eventos/3.mp4",
      "/videos/eventos/4.mp4",
      "/videos/eventos/5.mp4",
      "/videos/eventos/6.mp4",
      "/videos/eventos/7.mp4",
      "/videos/eventos/8.mp4",
    ],
    description: "Servicio completo de ambientación para eventos especiales. Creamos espacios únicos y memorables con arreglos florales personalizados, decoración temática y un ambiente perfecto para cada ocasión. Nuestro equipo se encarga de todos los detalles para que tu evento sea inolvidable.",
    specifications: {
      "Tipo de servicio": "Ambientación completa",
      "Incluye": "Arreglos florales, decoración, montaje",
      "Duración del evento": "Día completo",
      "Personalización": "Completamente adaptable",
      "Equipo": "Profesional especializado",
      "Ocasión": "Bodas, celebraciones, corporativos",
    },
  },
  "29": {
    id: "29",
    name: "AMBIENTACIÓN DE CUMPLEAÑOS",
    price: 0,
    image: "/videos/cumpleanos/1.mp4",
    category: "Ambientación de Cumpleaños",
    inStock: true,
    gallery: [],
    videos: [
      "/videos/cumpleanos/1.mp4",
    ],
    description: "Ambientación especial para celebraciones de cumpleaños que transforma cualquier espacio en un lugar mágico. Diseños personalizados según la edad, gustos y temática preferida, creando recuerdos inolvidables para el homenajeado y sus invitados.",
    specifications: {
      "Tipo de servicio": "Ambientación temática",
      "Incluye": "Decoración, arreglos, globos, detalles",
      "Personalización": "Según edad y preferencias",
      "Montaje": "Profesional",
      "Duración": "Evento completo",
      "Ocasión": "Cumpleaños de todas las edades",
    },
  },
  "30": {
    id: "30",
    name: "AMBIENTACIÓN DE IGLESIAS",
    price: 0,
    image: "/videos/iglesias/1.mp4",
    category: "Ambientación de Iglesias",
    inStock: true,
    gallery: [
      "/videos/iglesias/foto1.jpg",
      "/videos/iglesias/foto2.jpg",
    ],
    videos: [
      "/videos/iglesias/1.mp4",
      "/videos/iglesias/2.mp4",
    ],
    description: "Servicio especializado en ambientación para ceremonias religiosas y eventos en iglesias. Respetamos la solemnidad del espacio sagrado mientras creamos una atmósfera hermosa y apropiada con arreglos florales elegantes y decoración respetuosa.",
    specifications: {
      "Tipo de servicio": "Ambientación religiosa",
      "Incluye": "Arreglos de altar, pasillos, entrada",
      "Estilo": "Elegante y respetuoso",
      "Flores": "Seleccionadas apropiadamente",
      "Montaje": "Discreto y profesional",
      "Ocasión": "Bodas, bautizos, confirmaciones",
    },
  },
  "31": {
    id: "31",
    name: "SERVICIO SEMANAL PREMIUM",
    price: 0,
    image: "/videos/servicio-semanal/1.mp4",
    category: "Servicio Semanal",
    inStock: true,
    gallery: [],
    videos: [
      "/videos/servicio-semanal/1.mp4",
    ],
    description: "Servicio semanal de arreglos florales frescos para mantener tus espacios siempre hermosos y renovados. Ideal para oficinas, hoteles, restaurantes o hogares que desean tener flores frescas constantemente sin preocuparse por el mantenimiento.",
    specifications: {
      "Frecuencia": "Semanal",
      "Incluye": "Arreglos frescos, mantenimiento, reemplazo",
      "Personalización": "Según espacios y preferencias",
      "Flores": "De temporada, siempre frescas",
      "Servicio": "Entrega y mantenimiento incluido",
      "Ideal para": "Oficinas, comercios, hogares",
    },
  },
}

// Función helper para obtener productos como array
export const getAllProducts = (): Product[] => {
  return Object.values(productsData).map(({ gallery, videos, description, specifications, colors, ...product }) => product)
}

// Función helper para obtener productos por categoría
export const getProductsByCategory = (category: string): Product[] => {
  return getAllProducts().filter(product => product.category === category)
}

// Función helper para obtener un producto por ID
export const getProductById = (id: string): ProductDetail | undefined => {
  return productsData[id]
}

// Función para obtener productos destacados (solo 4 para página principal)
export const getFeaturedProducts = (): Product[] => [
  {
    id: "10",
    name: "RAMO ROSAS",
    price: 0,
    image: "/FOTOS/PRIMAVERA VERANO/7 (ROSAS).jpg",
    category: "Ramos",
    inStock: true,
    featured: true,
  },
  {
    id: "28",
    name: "AMBIENTACIÓN DE EVENTOS",
    price: 0,
    image: "/videos/eventos/1.mp4",
    category: "Ambientación de Eventos",
    inStock: true,
  },
  {
    id: "30",
    name: "AMBIENTACIÓN DE IGLESIAS",
    price: 0,
    image: "/videos/iglesias/1.mp4",
    category: "Ambientación de Iglesias",
    inStock: true,
  },
  {
    id: "18",
    name: "RAMO CALAS",
    price: 0,
    image: "/FOTOS/PRIMAVERA VERANO/14 (CALAS).jpg",
    category: "Ramos",
    inStock: true,
    featured: true,
  },
]

// Productos recomendados por defecto
export const getRecommendedProducts = (): Product[] => [
  {
    id: "10",
    name: "RAMO ROSAS",
    price: 0,
    image: "/FOTOS/PRIMAVERA VERANO/7 (ROSAS).jpg",
    category: "Arreglos Florales",
    inStock: true,
  },
  {
    id: "18",
    name: "RAMO CALAS",
    price: 0,
    image: "/FOTOS/PRIMAVERA VERANO/14 (CALAS).jpg",
    category: "Arreglos Florales",
    inStock: true,
  },
  {
    id: "20",
    name: "RAMO PEONIAS",
    price: 0,
    image: "/FOTOS/PRIMAVERA VERANO/placeholder-peonias.jpg",
    category: "Arreglos Florales",
    inStock: true,
  },
]
